[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install -r requirements_webapp.txt']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'python lemon_squeeze_webapp.py'
